name: Running jobs

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  merge_pull_requests:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3.2.0

    - name: Setup python
      uses: actions/setup-python@v4.5.0
      with:
        python-version: '3.6.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: |
        python pr_bot.py --merge
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
